### ISSUE TITLE
人物數據庫 xml 文件中存在未轉義的&字符

### ISSUE THREAD

**Issue by CallMeNP** [ddbc/Authority-Databases#1]
請見 `authority_place/Buddhist_Studies_Place_Authority.xml`  第340858行，“`(Lahul&Spiti)`”，其中 `&` 字符應該轉寫成 `&amp;` 否則會影響xml解析。
同樣內容共出現6行。

勞煩核實是否需要修正。（不清楚該文件是否為代碼生成，所以沒有提交pull request。）

**Comment by RayCHOU** [comment]
您好，這裡已不再維護了，請使用：
https://github.com/DILA-edu/Authority-Databases
